name: dart_firebase_admin_example_server_app
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dart_firebase_admin:
    git:
      url: https://github.com/invertase/dart_firebase_admin.git
      path: packages/dart_firebase_admin
      ref: next
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dependency_overrides:
  googleapis_auth_utils:
    git:
      url: https://github.com/invertase/dart_firebase_admin.git
      path: packages/googleapis_auth_utils
      ref: next

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
