name: googleapis_auth_utils
description: Utilities for working with googleapis_auth package.
resolution: workspace
version: 0.1.0
repository: "https://github.com/invertase/dart_firebase_admin"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  googleapis_auth: ^1.3.0
  http: ^1.0.0
  meta: ^1.9.1

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.4
