name: googleapis_firestore
description: Google Cloud Firestore client library for Dart.
resolution: workspace
version: 0.1.0
repository: "https://github.com/invertase/dart_firebase_admin"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  googleapis: ^15.0.0
  googleapis_auth: ^1.3.0
  googleapis_auth_utils: ^0.1.0
  http: ^1.0.0
  intl: ^0.20.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.7
  test: ^1.24.4
